csgo: '"E:\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe"'
dota2: '"E:\Steam\steamapps\common\dota 2 beta\game\bin\win64\dota2.exe"'
epicgameslauncher: '"D:\EpicGames\Epic Games\Launcher\Engine\Binaries\Win32\EpicGamesLauncher.exe"'
overwolf: '"C:\Program Files\Overwolf\Overwolf.exe"'
steam: '"E:\Steam\steam.exe"'
telegram: '"E:\Telegram Desktop\Telegram.exe"'
Discord: '"C:\Users\jagub\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Discord Inc\Discord.lnk"'